added mobile tutorial
EngoEngine/engoengine.github.io pull request #31
Opened 2017-12-01 18:28 UTC by Noofbiz

how to build both an apk or java bindings via gomobile for engo

2018-01-22 22:10 UTC, otraore requested changes
Once these changes are made, lgtm.

2018-01-22 22:10 UTC, otraore commented on concepts/mobileBuilding.md
> +The `engo` game engine, and Go in general, has a two ways to build for a
`has a two ways` -> `has two ways`

2018-01-22 22:10 UTC, otraore commented on concepts/mobileBuilding.md
> +First, you'll need to [install goMobile] (https://github.com/golang/go/wiki/Mobile).
`goMobile` -> `Go Mobile` 

This a bit picky but it looks better and is how it's used on the gomobile GitHub

2018-01-22 22:10 UTC, otraore commented on concepts/mobileBuilding.md
> +Facebook or adMob's sdks. This includes things like gradle and pro-guard
`adMob` -> `AdMob`

Again this is picky, up to you at the end of the day

2018-01-23 15:09 UTC, Noofbiz commented
Fixed! Thanks for the help

2018-03-14 17:19 UTC, Noofbiz commented
Ping ^_^

2018-03-26 14:08 UTC, merged